# Generated by Django 3.0.5 on 2020-04-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200428_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='u_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='u_birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
